name:                p4haskell
version:             0.0.0
github:              "nitros12/p4haskell"
homepage:            https://github.com/nitros12/p4haskell
bug-reports:         https://github.com/nitros12/p4haskell/issues
license:             MIT
license-file:        LICENSE
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           2019 Ben Simms
category:            Parsing Development Compilers/Interpreters Utility
build-type:          Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with:         GHC == 8.8.2


synopsis:            P4 backend in haskell
description:         P4 backend in haskell


dependencies:
  - base-noprelude >= 4.12 && < 5
  - relude ^>= 0.7
  - waargonaut ^>= 0.8
  - lens >= 4.18 && < 4.20
  - generic-lens ^>= 2
  - generic-monoid ^>= 0.1
  - unordered-containers ^>= 0.2
  - ordered-containers ^>= 0.2
  - di-polysemy ^>= 0.2
  - di ^>= 1.3
  - df1 >= 0.3 && < 0.5
  - polysemy ^>= 1.3
  - polysemy-zoo ^>= 0.7
  - polysemy-plugin ^>= 0.2
  - text ^>= 1.2
  - pretty
  - pretty-simple ^>= 3.3
  - bytestring ^>= 0.10
  - attoparsec ^>= 0.13
  - dependent-sum-template ^>= 0.1
  - hashable ^>= 1.3
  - some ^>= 1.0
  - rock ^>= 0.3
  - generics-sop ^>= 0.5
  - PyF
  - mtl
  - semigroupoids
  - language-c99 ^>= 0.1
  - language-c99-simple ^>= 0.1
  - extra ^>= 1.7
  - bitvec ^>= 1.0
  - vector ^>= 0.12

executables:
  p4haskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -fplugin=Polysemy.Plugin
      - -O2
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
    dependencies:
      - p4haskell
      - optparse-applicative

library:
    ghc-options:
      - -fplugin=Polysemy.Plugin
      - -O2
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
    source-dirs: src

tests:
  p4haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -fplugin=Polysemy.Plugin
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
    dependencies:
      - p4haskell

default-extensions:
  - IncoherentInstances
  - TemplateHaskell
  - RecursiveDo
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
  - PatternSynonyms
